# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9f239c9bd0d38f54554412120daccaca3b53ac1ebb1d1bf34376d329ae34ed8911f76f77a1ceabbb22addd06bb16240c111e141545860b82a9a4c7143baba73

test:
  secret_key_base: c9c2da166a4b86dc59733d4ba0f60e855fbe6a9d8ecab4555cda6e45cce469658db48cb4c9f1fd897ced5efba9d884b5f41e1b4167ea889b66b1271e8716888e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
